name: scd_implementations
version: "1.0.0"
config-version: 2

profile: scd_implementations

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  scd_implementations:
    +materialized: table
    +schema: scd_lab
